export const languageCodes: {
  [localeCode: string]: {
    name_english: string;
    name_native?: string;
    emoji?: string;
  };
} = {
  af: { name_english: "Afrikaans", name_native: "Afrikaans", emoji: "🇿🇦" },
  sq: { name_english: "Albanian", name_native: "Shqip", emoji: "🇦🇱" },
  "ar-DZ": {
    name_english: "Arabic (Algeria)",
    name_native: "العربية (الجزائر)",
    emoji: "🇩🇿",
  },
  "ar-BH": {
    name_english: "Arabic (Bahrain)",
    name_native: "العربية (البحرين)",
    emoji: "🇧🇭",
  },
  "ar-EG": {
    name_english: "Arabic (Egypt)",
    name_native: "العربية (مصر)",
    emoji: "🇪🇬",
  },
  "ar-IQ": {
    name_english: "Arabic (Iraq)",
    name_native: "العربية (العراق)",
    emoji: "🇮🇶",
  },
  "ar-JO": {
    name_english: "Arabic (Jordan)",
    name_native: "العربية (الأردن)",
    emoji: "🇯🇴",
  },
  "ar-KW": {
    name_english: "Arabic (Kuwait)",
    name_native: "العربية (الكويت)",
    emoji: "🇰🇼",
  },
  "ar-LB": {
    name_english: "Arabic (Lebanon)",
    name_native: "العربية (لبنان)",
    emoji: "🇱🇧",
  },
  "ar-LY": {
    name_english: "Arabic (Libya)",
    name_native: "العربية (ليبيا)",
    emoji: "🇱🇾",
  },
  "ar-MA": {
    name_english: "Arabic (Morocco)",
    name_native: "العربية (المغرب)",
    emoji: "🇲🇦",
  },
  "ar-OM": {
    name_english: "Arabic (Oman)",
    name_native: "العربية (عمان)",
    emoji: "🇴🇲",
  },
  "ar-QA": {
    name_english: "Arabic (Qatar)",
    name_native: "العربية (قطر)",
    emoji: "🇶🇦",
  },
  "ar-SA": {
    name_english: "Arabic (Saudi Arabia)",
    name_native: "العربية (السعودية)",
    emoji: "🇸🇦",
  },
  "ar-SY": {
    name_english: "Arabic (Syria)",
    name_native: "العربية (سوريا)",
    emoji: "🇸🇾",
  },
  "ar-TN": {
    name_english: "Arabic (Tunisia)",
    name_native: "العربية (تونس)",
    emoji: "🇹🇳",
  },
  "ar-AE": {
    name_english: "Arabic (U.A.E.)",
    name_native: "العربية (الإمارات)",
    emoji: "🇦🇪",
  },
  "ar-YE": {
    name_english: "Arabic (Yemen)",
    name_native: "العربية (اليمن)",
    emoji: "🇾🇪",
  },
  eu: { name_english: "Basque", name_native: "Euskara" },
  be: { name_english: "Belarusian", name_native: "Беларуская", emoji: "🇧🇾" },
  bg: { name_english: "Bulgarian", name_native: "Български", emoji: "🇧🇬" },
  ca: { name_english: "Catalan", name_native: "Català", emoji: "🇦🇩" },
  "zh-HK": {
    name_english: "Chinese (Hong Kong)",
    name_native: "中文 (香港)",
    emoji: "🇭🇰",
  },
  "zh-CN": {
    name_english: "Chinese (PRC)",
    name_native: "中文 (中国)",
    emoji: "🇨🇳",
  },
  "zh-SG": {
    name_english: "Chinese (Singapore)",
    name_native: "中文 (新加坡)",
    emoji: "🇸🇬",
  },
  "zh-TW": {
    name_english: "Chinese (Taiwan)",
    name_native: "中文 (台灣)",
    emoji: "🇹🇼",
  },
  hr: { name_english: "Croatian", name_native: "Hrvatski", emoji: "🇭🇷" },
  cs: { name_english: "Czech", name_native: "Čeština", emoji: "🇨🇿" },
  da: { name_english: "Danish", name_native: "Dansk", emoji: "🇩🇰" },
  "nl-BE": {
    name_english: "Dutch (Belgium)",
    name_native: "Nederlands (België)",
    emoji: "🇧🇪",
  },
  nl: {
    name_english: "Dutch",
    name_native: "Nederlands",
    emoji: "🇳🇱",
  },
  en: { name_english: "English", name_native: "English" },
  "en-AU": {
    name_english: "English (Australia)",
    name_native: "English (Australia)",
    emoji: "🇦🇺",
  },
  "en-BZ": {
    name_english: "English (Belize)",
    name_native: "English (Belize)",
    emoji: "🇧🇿",
  },
  "en-CA": {
    name_english: "English (Canada)",
    name_native: "English (Canada)",
    emoji: "🇨🇦",
  },
  "en-IE": {
    name_english: "English (Ireland)",
    name_native: "English (Ireland)",
    emoji: "🇮🇪",
  },
  "en-JM": {
    name_english: "English (Jamaica)",
    name_native: "English (Jamaica)",
    emoji: "🇯🇲",
  },
  "en-NZ": {
    name_english: "English (New Zealand)",
    name_native: "English (New Zealand)",
    emoji: "🇳🇿",
  },
  "en-ZA": {
    name_english: "English (South Africa)",
    name_native: "English (South Africa)",
    emoji: "🇿🇦",
  },
  "en-TT": {
    name_english: "English (Trinidad)",
    name_native: "English (Trinidad)",
    emoji: "🇹🇹",
  },
  "en-GB": {
    name_english: "English (United Kingdom)",
    name_native: "English (United Kingdom)",
    emoji: "🇬🇧",
  },
  "en-US": {
    name_english: "English (United States)",
    name_native: "English (United States)",
    emoji: "🇺🇸",
  },
  et: { name_english: "Estonian", name_native: "Eesti", emoji: "🇪🇪" },
  fo: { name_english: "Faeroese", name_native: "Føroyskt", emoji: "🇫🇴" },
  fa: { name_english: "Farsi", name_native: "فارسی", emoji: "🇮🇷" },
  fi: { name_english: "Finnish", name_native: "Suomi", emoji: "🇫🇮" },
  "fr-BE": {
    name_english: "French (Belgium)",
    name_native: "Français (Belgique)",
    emoji: "🇧🇪",
  },
  "fr-CA": {
    name_english: "French (Canada)",
    name_native: "Français (Canada)",
    emoji: "🇨🇦",
  },
  "fr-LU": {
    name_english: "French (Luxembourg)",
    name_native: "Français (Luxembourg)",
    emoji: "🇱🇺",
  },
  fr: {
    name_english: "French",
    name_native: "Français",
    emoji: "🇫🇷",
  },
  "fr-CH": {
    name_english: "French (Switzerland)",
    name_native: "Français (Suisse)",
    emoji: "🇨🇭",
  },
  gd: { name_english: "Gaelic (Scotland)", name_native: "Gàidhlig (Alba)" },
  "de-AT": {
    name_english: "German (Austria)",
    name_native: "Deutsch (Österreich)",
    emoji: "🇦🇹",
  },
  "de-LI": {
    name_english: "German (Liechtenstein)",
    name_native: "Deutsch (Liechtenstein)",
    emoji: "🇱🇮",
  },
  "de-LU": {
    name_english: "German (Luxembourg)",
    name_native: "Deutsch (Luxemburg)",
    emoji: "🇱🇺",
  },
  de: { name_english: "German", name_native: "Deutsch" },
  "de-CH": {
    name_english: "German (Switzerland)",
    name_native: "Schwiizerdütsch",
    emoji: "🇨🇭",
  },
  el: { name_english: "Greek", name_native: "Ελληνικά", emoji: "🇬🇷" },
  he: { name_english: "Hebrew", name_native: "עברית", emoji: "🇮🇱" },
  hi: { name_english: "Hindi", name_native: "हिन्दी", emoji: "🇮🇳" },
  hu: { name_english: "Hungarian", name_native: "Magyar", emoji: "🇭🇺" },
  is: { name_english: "Icelandic", name_native: "Íslenska", emoji: "🇮🇸" },
  id: {
    name_english: "Indonesian",
    name_native: "Bahasa Indonesia",
    emoji: "🇮🇩",
  },
  ga: { name_english: "Irish", name_native: "Gaeilge", emoji: "🇮🇪" },
  it: {
    name_english: "Italian",
    name_native: "Italiano",
    emoji: "🇮🇹",
  },
  "it-CH": {
    name_english: "Italian (Switzerland)",
    name_native: "Italiano (Svizzera)",
    emoji: "🇨🇭",
  },
  ja: { name_english: "Japanese", name_native: "日本語", emoji: "🇯🇵" },
  ko: { name_english: "Korean (Johab)", name_native: "한국어", emoji: "🇰🇷" },
  ku: { name_english: "Kurdish", name_native: "Kurdî" },
  lv: { name_english: "Latvian", name_native: "Latviešu", emoji: "🇱🇻" },
  lt: { name_english: "Lithuanian", name_native: "Lietuvių", emoji: "🇱🇹" },
  mk: {
    name_english: "Macedonian (FYROM)",
    name_native: "Македонски",
    emoji: "🇲🇰",
  },
  ml: { name_english: "Malayalam", name_native: "മലയാളം" },
  ms: {
    name_english: "Malaysian",
    name_native: "Bahasa Malaysia",
    emoji: "🇲🇾",
  },
  mt: { name_english: "Maltese", name_native: "Malti", emoji: "🇲🇹" },
  no: { name_english: "Norwegian", name_native: "Norsk", emoji: "🇳🇴" },
  nb: {
    name_english: "Norwegian (Bokmål)",
    name_native: "Norsk (Bokmål)",
    emoji: "🇳🇴",
  },
  nn: {
    name_english: "Norwegian (Nynorsk)",
    name_native: "Norsk (Nynorsk)",
    emoji: "🇳🇴",
  },
  pl: { name_english: "Polish", name_native: "Polski", emoji: "🇵🇱" },
  "pt-BR": {
    name_english: "Portuguese (Brazil)",
    name_native: "Português (Brasil)",
    emoji: "🇧🇷",
  },
  pt: {
    name_english: "Portuguese (Portugal)",
    name_native: "Português (Portugal)",
    emoji: "🇵🇹",
  },
  pa: { name_english: "Punjabi", name_native: "ਪੰਜਾਬੀ" },
  rm: { name_english: "Rhaeto-Romanic", name_native: "Rumantsch" },
  ro: { name_english: "Romanian", name_native: "Română", emoji: "🇷🇴" },
  "ro-MD": {
    name_english: "Romanian (Republic of Moldova)",
    name_native: "Română (Republica Moldova)",
    emoji: "🇲🇩",
  },
  ru: { name_english: "Russian", name_native: "Русский", emoji: "🇷🇺" },
  "ru-MD": {
    name_english: "Russian (Republic of Moldova)",
    name_native: "Русский (Республика Молдова)",
    emoji: "🇲🇩",
  },
  sr: { name_english: "Serbian", name_native: "Српски", emoji: "🇷🇸" },
  sk: { name_english: "Slovak", name_native: "Slovenčina", emoji: "🇸🇰" },
  sl: { name_english: "Slovenian", name_native: "Slovenščina", emoji: "🇸🇮" },
  sb: { name_english: "Sorbian", name_native: "Serbšćina" },
  "es-AR": {
    name_english: "Spanish (Argentina)",
    name_native: "Español (Argentina)",
    emoji: "🇦🇷",
  },
  "es-BO": {
    name_english: "Spanish (Bolivia)",
    name_native: "Español (Bolivia)",
    emoji: "🇧🇴",
  },
  "es-CL": {
    name_english: "Spanish (Chile)",
    name_native: "Español (Chile)",
    emoji: "🇨🇱",
  },
  "es-CO": {
    name_english: "Spanish (Colombia)",
    name_native: "Español (Colombia)",
    emoji: "🇨🇴",
  },
  "es-CR": {
    name_english: "Spanish (Costa Rica)",
    name_native: "Español (Costa Rica)",
    emoji: "🇨🇷",
  },
  "es-DO": {
    name_english: "Spanish (Dominican Republic)",
    name_native: "Español (República Dominicana)",
    emoji: "🇩🇴",
  },
  "es-EC": {
    name_english: "Spanish (Ecuador)",
    name_native: "Español (Ecuador)",
    emoji: "🇪🇨",
  },
  "es-SV": {
    name_english: "Spanish (El Salvador)",
    name_native: "Español (El Salvador)",
    emoji: "🇸🇻",
  },
  "es-GT": {
    name_english: "Spanish (Guatemala)",
    name_native: "Español (Guatemala)",
    emoji: "🇬🇹",
  },
  "es-HN": {
    name_english: "Spanish (Honduras)",
    name_native: "Español (Honduras)",
    emoji: "🇭🇳",
  },
  "es-MX": {
    name_english: "Spanish (Mexico)",
    name_native: "Español (México)",
    emoji: "🇲🇽",
  },
  "es-NI": {
    name_english: "Spanish (Nicaragua)",
    name_native: "Español (Nicaragua)",
    emoji: "🇳🇮",
  },
  "es-PA": {
    name_english: "Spanish (Panama)",
    name_native: "Español (Panamá)",
    emoji: "🇵🇦",
  },
  "es-PY": {
    name_english: "Spanish (Paraguay)",
    name_native: "Español (Paraguay)",
    emoji: "🇵🇾",
  },
  "es-PE": {
    name_english: "Spanish (Peru)",
    name_native: "Español (Perú)",
    emoji: "🇵🇪",
  },
  "es-PR": {
    name_english: "Spanish (Puerto Rico)",
    name_native: "Español (Puerto Rico)",
    emoji: "🇵🇷",
  },
  es: {
    name_english: "Spanish",
    name_native: "Español",
  },
  "es-EN": {
    name_english: "Spanish (Spain)",
    name_native: "Español (España)",
    emoji: "🇪🇸",
  },
  "es-UY": {
    name_english: "Spanish (Uruguay)",
    name_native: "Español (Uruguay)",
    emoji: "🇺🇾",
  },
  "es-VE": {
    name_english: "Spanish (Venezuela)",
    name_native: "Español (Venezuela)",
    emoji: "🇻🇪",
  },
  sv: { name_english: "Swedish", name_native: "Svenska", emoji: "🇸🇪" },
  "sv-FI": {
    name_english: "Swedish (Finland)",
    name_native: "Svenska (Finland)",
    emoji: "🇫🇮",
  },
  th: { name_english: "Thai", name_native: "ไทย", emoji: "🇹🇭" },
  ts: { name_english: "Tsonga", name_native: "Xitsonga" },
  tn: { name_english: "Tswana", name_native: "Setswana" },
  tr: { name_english: "Turkish", name_native: "Türkçe", emoji: "🇹🇷" },
  uk: { name_english: "Ukrainian", name_native: "Українська", emoji: "🇺🇦" },
  ur: { name_english: "Urdu", name_native: "اردو", emoji: "🇵🇰" },
  ve: { name_english: "Venda", name_native: "Tshivenḓa" },
  vi: { name_english: "Vietnamese", name_native: "Tiếng Việt", emoji: "🇻🇳" },
  cy: { name_english: "Welsh", name_native: "Cymraeg", emoji: "🏴󠁧󠁢󠁷󠁬󠁿" },
  xh: { name_english: "Xhosa", name_native: "isiXhosa", emoji: "🇿🇦" },
  ji: { name_english: "Yiddish", name_native: "ייִדיש" },
  zu: { name_english: "Zulu", name_native: "isiZulu", emoji: "🇿🇦" },
};
