import { environment } from "../environments/environment";

/**
 * Valid profile picture sizes that are generated by the image processing function.
 */
export type ProfilePictureSize = 200 | 400 | 800;

const PROFILE_PICTURES_BUCKET = "profile_pictures";

/**
 * Generates a predictable, token-free profile picture URL for a user.
 * Since profile pictures are public and use the user ID as filename,
 * we can derive the URL from just the user ID without needing to store it.
 *
 * @param userId - The user's UID
 * @param size - Optional size for resized versions (200, 400, or 800 pixels)
 * @returns The Firebase Storage URL for the profile picture
 */
export function getProfilePictureUrl(
  userId: string,
  size?: ProfilePictureSize
): string {
  if (!userId) {
    return "";
  }

  const bucket = environment.keys.firebaseConfig.storageBucket;
  const sizeSuffix = size ? `_${size}x${size}` : "";
  const filename = `${userId}${sizeSuffix}`;
  const encodedPath = encodeURIComponent(
    `${PROFILE_PICTURES_BUCKET}/${filename}`
  );

  return `https://firebasestorage.googleapis.com/v0/b/${bucket}/o/${encodedPath}?alt=media`;
}

/**
 * Checks if a user has a profile picture by attempting a HEAD request.
 * This is useful for showing a placeholder while the picture loads or if none exists.
 *
 * @param userId - The user's UID
 * @param size - Size to check (defaults to 200)
 * @returns Promise that resolves to true if the profile picture exists
 */
export async function hasProfilePicture(
  userId: string,
  size: ProfilePictureSize = 200
): Promise<boolean> {
  if (!userId) {
    return false;
  }

  const url = getProfilePictureUrl(userId, size);

  try {
    const response = await fetch(url, { method: "HEAD" });
    return response.ok;
  } catch {
    return false;
  }
}
