const assert = require('node:assert/strict');
const {createRequire} = require('node:module');
const {resolve} = require('node:path');
const {readFile} = require('node:fs/promises');
const requireFunctions = createRequire(resolve('functions/package.json'));
if (!process.env.FIRESTORE_EMULATOR_HOST || !process.env.FIREBASE_STORAGE_EMULATOR_HOST || !process.env.GCLOUD_PROJECT?.startsWith('demo-')) throw Error('Demo Firestore and Storage emulators required');
const admin = requireFunctions('firebase-admin');
admin.initializeApp({projectId:process.env.GCLOUD_PROJECT,storageBucket:`${process.env.GCLOUD_PROJECT}.appspot.com`});
const db=admin.firestore(), bucket=admin.storage().bucket();
const {prepareShareCard,shareCardImage,invalidateSpotShareCard}=require('../../functions/lib/functions/src/shareCards/functions.js');
const renderer=require('../../functions/lib/functions/src/shareCards/render.js');
const express=require('express');
const app=express(); app.get('/image',shareCardImage);
const server=app.listen(0,'127.0.0.1');
const call = id => prepareShareCard.run({data:{kind:'spot',id},rawRequest:{ip:'127.0.0.1'}});
const image = async id => fetch(`http://127.0.0.1:${server.address().port}/image?kind=spot&id=${id}`);
async function run(){
  const id='share-test', ref=db.doc(`spots/${id}`);
  await ref.set({name:{en:{text:'Fixture Spot'}},rating:0,address:{locality:'Test town'}});
  const first=await call(id); assert.equal(first.reused,false);
  const cards=await db.collection('share_cards').get(); assert.equal(cards.size,1);
  let card=cards.docs[0].data(); assert.ok(card.path.startsWith('share_cards/spots/'));
  const [metadata]=await bucket.file(card.path).getMetadata();
  assert.equal(metadata.metadata?.firebaseStorageDownloadTokens,undefined);
  assert.equal((await image(id)).status,200);
  assert.equal((await call(id)).reused,true);
  const direct=await fetch(`http://${process.env.FIREBASE_STORAGE_EMULATOR_HOST}/v0/b/${bucket.name}/o/${encodeURIComponent(card.path)}?alt=media`);
  assert.ok([401,403].includes(direct.status),'Anonymous Storage reads must be denied');
  const firestoreRead=await fetch(`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/${process.env.GCLOUD_PROJECT}/databases/(default)/documents/share_cards/${cards.docs[0].id}`);
  assert.equal(firestoreRead.status,403,'Card records are server-owned');
  const photo=await readFile('src/assets/banner_1200x630.png');
  const photoPath='spot_pictures/share-test_800x800.png';
  await bucket.file(photoPath).save(photo,{resumable:false,metadata:{contentType:'image/png'}});
  await ref.update({media:[{type:'image',src:'spot_pictures/share-test.png',isInStorage:true}]});
  assert.equal((await call(id)).reused,false);
  assert.equal((await bucket.file(card.path).exists())[0],false,'Replaced card removed');
  card=(await cards.docs[0].ref.get()).data();
  assert.equal(card.media[0].path,photoPath,'Use published resize even when original is archived');
  await bucket.file(photoPath).delete();
  assert.deepEqual(Buffer.from(await (await image(id)).arrayBuffer()),photo,'Removed media is not served from the old card');
  assert.equal((await call(id)).reused,false);
  card=(await cards.docs[0].ref.get()).data();
  await bucket.file(card.path).delete();
  assert.equal((await call(id)).reused,false,'Missing generated image is repaired');
  card=(await cards.docs[0].ref.get()).data();
  const before=await ref.get(); await ref.update({visibility:'private'}); const after=await ref.get();
  assert.equal((await image(id)).status,404,'Privacy blocks reads before cleanup runs');
  await assert.rejects(call(id),error=>error.code==='permission-denied');
  await invalidateSpotShareCard.run({params:{id},data:{before,after}});
  assert.equal((await bucket.file(card.path).exists())[0],false);
  assert.equal((await cards.docs[0].ref.get()).exists,false);
  // Change privacy while rendering: publication must re-read source atomically.
  await ref.update({visibility:'public'});
  const original=renderer.renderShareCard;
  renderer.renderShareCard=async (...args)=>{ await ref.update({visibility:'private'}); return original(...args); };
  await assert.rejects(call(id),error=>error.code==='aborted');
  renderer.renderShareCard=original;
  assert.equal((await bucket.getFiles({prefix:'share_cards/'}))[0].length,0,'Aborted uploads are removed');
  console.log('Share-card emulator checks passed: prepare, reuse, private storage, privacy gate, deletion, publication race.');
}
run().finally(async()=>{server.close();await admin.app().delete();}).catch(error=>{console.error(error);process.exitCode=1;});
